In [ ]:
import pickle
with open('gladiator_sentence_transformer.pkl', 'rb') as f:
    gladiator = pickle.load(f)







In [ ]:
len(gladiator[6])


10

In [ ]:
import numpy as np
length = []

for i in range(0, len(gladiator)):
    length.append(len(gladiator[i]))




X = []

for i in range(0, len(gladiator)):
    for j in range(0, len(gladiator[i])):
        X.append(np.array(gladiator[i][j]))



In [ ]:
print(X[45][4])

0.1711742


In [ ]:
%pip install hmmlearn

     |████████████████████████████████| 374 kB 12.4 MB/s 


In [ ]:
from hmmlearn import hmm

In [ ]:
remodel = hmm.GaussianHMM(n_components=4, n_iter = 50, covariance_type = 'diag', verbose = True, init_params="cm", params="cmts")
remodel.startprob_ = np.array([1, 0.0, 0.0, 0.0])
remodel.transmat_ = np.array([
                 [0.33, 0.34, 0.33, 0.0],
                 [ 0.0, 0.33, 0.34, 0.33],
                 [0.0, 0.0, 0.5, 0.5],
                 [0.0, 0.0, 0.0, 1.0]]
                            )

In [ ]:
remodel.startprob_

array([1., 0., 0., 0.])

In [ ]:
remodel.transmat_

array([[0.33, 0.34, 0.33, 0.  ],
       [0.  , 0.33, 0.34, 0.33],
       [0.  , 0.  , 0.5 , 0.5 ],
       [0.  , 0.  , 0.  , 1.  ]])

In [ ]:

remodel.fit(X, length)

         1     -379915.8535             +nan
         2     -357805.7808      +22110.0727
         3     -357805.5645          +0.2163
         4     -357805.5645          -0.0000


GaussianHMM(init_params='cm', n_components=4, n_iter=50, params='cmts',
            verbose=True)

In [ ]:
remodel.transmat_

array([[9.92753623e-001, 7.24637681e-003, 4.43024350e-204,
        0.00000000e+000],
       [0.00000000e+000, 9.03225806e-001, 9.67741936e-002,
        1.97738954e-240],
       [0.00000000e+000, 0.00000000e+000, 8.18181818e-001,
        1.81818182e-001],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        1.00000000e+000]])

In [ ]:
remodel.startprob_

array([1., 0., 0., 0.])

In [ ]:
def encode_convs(profix):
    sent_label = []
    with open(profix + '_sentence_transformer.pkl', 'rb') as f:
        data = pickle.load(f)
    for i in range(0, len(data)):
        labels = remodel.decode(np.array(data[i]))[1]
        sent_label.append(labels)
    
    with open(profix + '_sent_trans_cons_label_2.pkl', 'wb') as f:
        pickle.dump(sent_label, f)
    return sent_label

In [ ]:
l = encode_convs('gladiator')

In [ ]:
l = encode_convs('CastAway')

AttributeError: ignored

In [ ]:
l = encode_convs('Cars2')