In [15]:
import pickle
with open('diehard_sentence_transformer.pkl', 'rb') as f:
    diehard = pickle.load(f)


In [17]:
import numpy as np
length = []
for i in range(0, len(diehard)):
    length.append(len(diehard[i]))

X = []
for i in range(0, len(diehard)):
    for j in range(0, len(diehard[i])):
        X.append(np.array(diehard[i][j]))



In [5]:
%pip install hmmlearn

     |████████████████████████████████| 374 kB 5.1 MB/s 


In [6]:
from hmmlearn import hmm

In [19]:
remodel = hmm.GaussianHMM(n_components=4, n_iter = 50, covariance_type = 'diag', verbose = True, init_params="cm", params="cmts")
remodel.startprob_ = np.array([1, 0.0, 0.0, 0.0])
remodel.transmat_ = np.array([
                 [0.33, 0.34, 0.33, 0.0],
                 [ 0.0, 0.33, 0.34, 0.33],
                 [0.0, 0.0, 0.5, 0.5],
                 [0.0, 0.0, 0.0, 1.0]]
                            )

In [20]:
remodel.startprob_

array([1., 0., 0., 0.])

In [21]:
remodel.transmat_

array([[0.33, 0.34, 0.33, 0.  ],
       [0.  , 0.33, 0.34, 0.33],
       [0.  , 0.  , 0.5 , 0.5 ],
       [0.  , 0.  , 0.  , 1.  ]])

In [22]:

remodel.fit(X, length)

         1    -1578379.9153             +nan
         2    -1519819.5245      +58560.3908
         3    -1486496.9613      +33322.5632
         4    -1452756.3390      +33740.6222
         5    -1450456.1594       +2300.1797
         6    -1444112.5081       +6343.6512
         7    -1438013.2542       +6099.2539
         8    -1429677.6066       +8335.6475
         9    -1423622.0987       +6055.5080
        10    -1418555.4522       +5066.6465
        11    -1418558.6624          -3.2102


GaussianHMM(init_params='cm', n_components=4, n_iter=50, params='cmts',
            verbose=True)

In [23]:
remodel.transmat_

array([[0.97191211, 0.01526516, 0.01282273, 0.        ],
       [0.        , 0.74193548, 0.0483871 , 0.20967742],
       [0.        , 0.        , 0.        , 1.        ],
       [0.        , 0.        , 0.        , 1.        ]])

In [24]:
remodel.startprob_

array([1., 0., 0., 0.])

In [25]:
def encode_convs(profix):
    sent_label = []
    with open(profix + '_sentence_transformer.pkl', 'rb') as f:
        data = pickle.load(f)
    for i in range(0, len(data)):
        labels = remodel.decode(np.array(data[i]))[1]
        sent_label.append(labels)
    
    with open(profix + '_sent_trans_cons_label_2.pkl', 'wb') as f:
        pickle.dump(sent_label, f)
    return sent_label

In [26]:
l = encode_convs('diehard')